id: org.freedesktop.Sdk.Extension.cssls
default-branch: 20.08
sdk: org.freedesktop.Sdk//20.08
sdk-extensions:
  - org.freedesktop.Sdk.Extension.node14
runtime: org.freedesktop.Sdk
runtime-version: 20.08
build-extension: true
appstream-compose: false
modules:

  - name: node
    buildsystem: simple
    build-commands:
      - '/usr/lib/sdk/node14/install-sdk.sh'

  - name: cssls
    buildsystem: simple
    build-options:
      build-args:
        - '--share=network'
      append-path: '/usr/lib/sdk/node14/bin:./node_modules/.bin'
      env:
        npm_config_nodedir: /usr/lib/sdk/node14
    build-commands:
      - npm install --cache=/run/build/cssls/npm-cache vscode-css-languageserver-bin
      - mkdir -p /usr/lib/sdk/cssls/main
      - cp -ra ./* /usr/lib/sdk/cssls/main

  - name: vscode-css-languageserver
    buildsystem: simple
    build-commands:
      - install -Dm 755 run.sh /usr/lib/sdk/cssls/bin/css-languageserver
    sources:
      - type: script
        dest-filename: run.sh
        commands:
          - source /usr/lib/sdk/cssls/node/enable.sh
          - node /usr/lib/sdk/cssls/main/node_modules/vscode-css-languageserver-bin/cssServerMain.js $@

  - name: metadata
    buildsystem: simple
    build-commands:
      - install -Dm644 -t ${FLATPAK_DEST}/share/metainfo ${FLATPAK_ID}.metainfo.xml
      - appstream-compose --basename=${FLATPAK_ID} --prefix=${FLATPAK_DEST} --origin=flatpak ${FLATPAK_ID}
    sources:
      - type: file
        path: org.freedesktop.Sdk.Extension.cssls.metainfo.xml
