id: org.freedesktop.Sdk.Extension.fzf
default-branch: 20.08
sdk: org.freedesktop.Sdk//20.08
runtime: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.golang
runtime-version: 20.08
build-extension: true
appstream-compose: false
modules:

  - name: fzf
    buildsystem: simple
    build-options:
        build-args:
            - "--share=network"
        append-path: /usr/lib/sdk/golang/bin
        env:
            GOROOT: /usr/lib/sdk/golang
            FZF_VERSION: master
    build-commands:
      - make
      - install -Dm755 target/fzf-linux_amd64 /usr/lib/sdk/fzf/bin/fzf
    sources:
      - type: git
        url: https://github.com/junegunn/fzf 
        tag: master

  - name: metadata
    buildsystem: simple
    build-commands:
      - install -Dm644 -t ${FLATPAK_DEST}/share/metainfo ${FLATPAK_ID}.metainfo.xml
      - appstream-compose --basename=${FLATPAK_ID} --prefix=${FLATPAK_DEST} --origin=flatpak ${FLATPAK_ID}
    sources:
      - type: file
        path: org.freedesktop.Sdk.Extension.fzf.metainfo.xml
