id: org.freedesktop.Sdk.Extension.code-minimap
default-branch: 20.08
sdk: org.freedesktop.Sdk//20.08
sdk-extensions: 
    - org.freedesktop.Sdk.Extension.rust-stable
runtime: org.freedesktop.Sdk
runtime-version: 20.08
build-extension: true
appstream-compose: false
modules:

  - name: code-minimap
    buildsystem: simple
    build-options:
        build-args:
            - "--share=network"
        append-path: /usr/lib/sdk/rust-stable/bin
        env:
            CARGO_HOME: /run/build/code-minimap/cargo
    build-commands:
        - cargo build --release
        - install -D -m 755 ./target/release/code-minimap -t /usr/lib/sdk/code-minimap/bin
    sources:
      - type: git
        url: https://github.com/wfxr/code-minimap
        tag: master

  - name: metadata
    buildsystem: simple
    build-commands:
      - install -Dm644 -t ${FLATPAK_DEST}/share/metainfo ${FLATPAK_ID}.metainfo.xml
      - appstream-compose --basename=${FLATPAK_ID} --prefix=${FLATPAK_DEST} --origin=flatpak ${FLATPAK_ID}
    sources:
      - type: file
        path: org.freedesktop.Sdk.Extension.code-minimap.metainfo.xml
